### ISSUE TITLE
No longer hosted?

### ISSUE THREAD

**Issue by OJFord** [tonton-pixel/tutti-quanti-shelf#4]
Hi, thanks for these, I'm here because I used to have one bookmarked on your site, which now redirects to your GH profile.

Just wondering if they're still hosted anywhere? (Which would be handy to link from readme for someone just wanting a quick reference of one of the former 'goodies' rather than installing something to use once, or at least not very frequently 🙂)

Cheers!

**Comment by tonton-pixel** [comment]
Thanks for your interest in my projects.

Although I've kept my main domain name `tonton-pixel.com`, I don't own the other ones any more (`tonton-pixel.org`, `tonton-pixel.net`). And I don't have any more associated web hosting too.

If what you are interested in is the **JSON Photoshop Scripting** project, it is now archived on GitHub: [https://github.com/tonton-pixel/json-photoshop-scripting](https://github.com/tonton-pixel/json-photoshop-scripting).

 If it is something else, please let me know so that I can see if I can make it available in some way... Also, since you're mentioning "goodies", please tell me what you have in mind more specifically.

**Comment by OJFord** [comment]
It was http://www.tonton-pixel.com/goodies/cidr-calculator/index.html specifically that I had bookmarked.

There are similar tools about of course, just wanted to take the opportunity to thank you for it and slightly feedback about the relative friction of installing something vs. website really.

Thanks again though 🙂

**Comment by tonton-pixel** [comment]
@OJFord I did check a local copy of the page you mentioned, and noticed that it had a link to a self-contained HTML page which could be used offline (and bookmarked) once saved locally. Please find the attached zip-compressed file, in case it may be helpful...
[cidr.html.zip](https://github.com/tonton-pixel/tutti-quanti-shelf/files/5842966/cidr.html.zip)
